wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: huggingface
    huggingface_version: 4.2.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1643835017
    t:
      1:
      - 1
      - 5
      - 11
      2:
      - 1
      - 5
      - 11
      3:
      - 1
      - 13
      - 14
      - 16
      4: 3.7.12
      5: 0.12.10
      6: 4.2.2
      8:
      - 5
backbone_layers:
  desc: null
  value:
  - 2
  - 3
  - 7
batchsize:
  desc: null
  value: 10
betas:
  desc: null
  value:
  - 0.9
  - 0.999
bos_token:
  desc: null
  value: 1
channels:
  desc: null
  value: 1
data:
  desc: null
  value: dataset/data/train.pkl
debug:
  desc: null
  value: false
decoder_args:
  desc: null
  value:
    attn_on_attn: true
    cross_attend: true
    ff_glu: true
    rel_pos_bias: false
    use_scalenorm: false
device:
  desc: null
  value: cuda
dim:
  desc: null
  value: 256
encoder_depth:
  desc: null
  value: 4
eos_token:
  desc: null
  value: 2
epoch:
  desc: null
  value: 0
epochs:
  desc: null
  value: 1
gamma:
  desc: null
  value: 0.9995
heads:
  desc: null
  value: 8
id:
  desc: null
  value: 1yfegj76
load_chkpt:
  desc: null
  value: checkpoints/weights.pth
lr:
  desc: null
  value: 0.001
lr_step:
  desc: null
  value: 30
max_dimensions:
  desc: null
  value:
  - 672
  - 192
max_height:
  desc: null
  value: 192
max_seq_len:
  desc: null
  value: 512
max_width:
  desc: null
  value: 672
min_dimensions:
  desc: null
  value:
  - 32
  - 32
min_height:
  desc: null
  value: 32
min_width:
  desc: null
  value: 32
model_path:
  desc: null
  value: checkpoints
name:
  desc: null
  value: mixed
num_layers:
  desc: null
  value: 4
num_tokens:
  desc: null
  value: 8000
optimizer:
  desc: null
  value: Adam
out_path:
  desc: null
  value: checkpoints/mixed
output_path:
  desc: null
  value: outputs
pad:
  desc: null
  value: false
pad_token:
  desc: null
  value: 0
patch_size:
  desc: null
  value: 16
sample_freq:
  desc: null
  value: 2000
save_freq:
  desc: null
  value: 1
scheduler:
  desc: null
  value: StepLR
seed:
  desc: null
  value: 42
temperature:
  desc: null
  value: 0.2
test_samples:
  desc: null
  value: 5
testbatchsize:
  desc: null
  value: 20
tokenizer:
  desc: null
  value: dataset/tokenizer.json
valbatches:
  desc: null
  value: 100
valdata:
  desc: null
  value: dataset/data/val.pkl
wandb:
  desc: null
  value: true
